{{- if and .Values.token (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptimepage-agent.fullname" . }}-token
  labels:
    {{- include "uptimepage-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecretKey }}: {{ .Values.token | quote }}
{{- end }}
