ALTER TABLE plans DROP COLUMN IF EXISTS max_regions;
ALTER TABLE incidents DROP COLUMN IF EXISTS region;
DROP TABLE IF EXISTS agents;
DROP TABLE IF EXISTS target_regions;
DROP TABLE IF EXISTS regions;
