use utoipa::OpenApi;

use crate::api::error::{ApiError, ApiErrorBody};
use crate::api::handlers;
use crate::api::handlers::orgs::{
    CheckSlugResponse, CreateOrgRequest, MemberView as OrgMemberView, OrgView,
    SwitchActiveOrgRequest, UpdateOrgRequest,
};
use crate::api::page::PageEnvelope;
use crate::api::public_error::{PublicApiError, PublicApiErrorBody};
use crate::api::types::{
    BulkAction, BulkActionFailure, BulkActionRequest, BulkActionResponse, DashboardSummary,
    Last24hSummary, LatencyBucket, LatencySeries, StatusBreakdown, SystemSummary, TagCount,
    TargetsSummary, TestRequest, TestResponse,
};
use crate::domain::Role;
use crate::domain::{
    ActorType, AlertBinding, ChannelConfig, ChannelKind, CheckResult, CheckSpec, CheckStatus,
    ComponentHistoryResponse, DayState, DnsCheck, DnsRecordType, DomainExpiryCheck,
    EscalationPolicy, EscalationPolicySummary, EscalationStep, EscalationTarget,
    EscalationTargetType, ExpectedStatus, HttpCheck, HttpMethod, Incident, IncidentEvent,
    IncidentEventKind, IncidentNarrationUpdate, NewEscalationPolicy, NewEscalationStep,
    NewEscalationTarget,
    IncidentOrigin, IncidentSeverity, IncidentState, IncidentStatusPhase, IncidentUrgency,
    IncidentVisibility, MaintenanceFilter, MaintenanceWindow, MaintenanceWindowUpdate,
    NewIncidentUpdate, NewMaintenanceWindow, NewManualIncident, NewNotificationChannel, NewTarget,
    NotificationChannel, NotificationChannelUpdate, OpsIncident, OverallState, OverallStatus,
    PublicComponent, PublicComponentGroup, PublicComponentStatus, PublicIncident,
    PublicIncidentUpdate, PublicMaintenance, PublicMaintenanceList, PublicStatusPage, Target,
    TargetAlerts, TargetUpdate, TcpCheck, TlsCertCheck, WriteSource,
};
use crate::storage::UptimeStats;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "uptimepage",
        description = "HTTP / TCP / TLS-cert / domain-expiry / DNS health-check service. \
                       Schedules checks against configured targets, stores results, \
                       exposes a REST API.",
        license(name = "MIT"),
    ),
    servers((url = "/", description = "Current host")),
    paths(
        handlers::health::healthz,
        handlers::health::readyz,
        handlers::targets::create,
        handlers::targets::bulk_create,
        handlers::targets::list,
        handlers::targets::get,
        handlers::targets::update,
        handlers::targets::delete,
        handlers::targets::bulk_action,
        handlers::targets::test_check,
        handlers::targets::check_now,
        handlers::results::list_results,
        handlers::results::latency,
        handlers::results::uptime,
        handlers::results::list_incidents,
        handlers::tags::list_tags,
        handlers::dashboard::dashboard_summary,
        handlers::public::public_status,
        handlers::public::component_history,
        handlers::public::public_incidents,
        handlers::public::public_incident,
        handlers::public::public_incidents_rss,
        handlers::public::public_maintenance,
        handlers::public::public_badge,
        handlers::maintenance::create_maintenance,
        handlers::maintenance::list_maintenance,
        handlers::maintenance::get_maintenance,
        handlers::maintenance::update_maintenance,
        handlers::maintenance::delete_maintenance,
        handlers::notification_channels::create,
        handlers::notification_channels::list,
        handlers::notification_channels::get,
        handlers::notification_channels::update,
        handlers::notification_channels::delete,
        handlers::notification_channels::test_send,
        handlers::incidents::update_incident_narration,
        handlers::incidents::post_incident_update,
        handlers::incidents::list_incidents,
        handlers::incidents::get_incident,
        handlers::incidents::declare_incident,
        handlers::incidents::acknowledge_incident,
        handlers::incidents::resolve_incident,
        handlers::incidents::reopen_incident,
        handlers::incidents::assign_incident,
        handlers::incidents::add_incident_note,
        handlers::escalation_policies::list,
        handlers::escalation_policies::create,
        handlers::escalation_policies::get,
        handlers::escalation_policies::replace,
        handlers::escalation_policies::delete,
        handlers::escalation_policies::get_org_default,
        handlers::escalation_policies::set_org_default,
        handlers::escalation_policies::get_target_policy,
        handlers::escalation_policies::set_target_policy,
        handlers::orgs::create_org,
        handlers::orgs::list_my_orgs,
        handlers::orgs::list_my_deleted_orgs,
        handlers::orgs::get_org,
        handlers::orgs::update_org,
        handlers::orgs::delete_org,
        handlers::orgs::restore_org,
        handlers::orgs::check_slug,
        handlers::orgs::list_org_members,
        handlers::orgs::remove_org_member,
        handlers::orgs::switch_active_org,
        handlers::usage::get_org_usage,
        handlers::usage::get_me_usage,
        handlers::status_page::list_pages,
        handlers::status_page::create_page,
        handlers::status_page::get_page,
        handlers::status_page::update_page,
        handlers::status_page::delete_page,
        handlers::status_page::list_components,
        handlers::status_page::add_component,
        handlers::status_page::update_component,
        handlers::status_page::remove_component,
        handlers::status_page::reorder_components,
        handlers::status_page::upload_logo,
        handlers::status_page::delete_logo,
        handlers::shares::create_share,
        handlers::shares::list_shares,
        handlers::shares::revoke_share,
        handlers::account::data_export,
        handlers::account::delete_account,
        handlers::api_tokens::list,
        handlers::api_tokens::create,
        handlers::api_tokens::rename,
        handlers::api_tokens::revoke,
    ),
    components(
        schemas(
            ApiError,
            ApiErrorBody,
            handlers::health::HealthResponse,
            Target,
            NewTarget,
            TargetUpdate,
            CheckSpec,
            HttpCheck,
            TcpCheck,
            TlsCertCheck,
            DomainExpiryCheck,
            DnsCheck,
            DnsRecordType,
            HttpMethod,
            ExpectedStatus,
            CheckResult,
            CheckStatus,
            WriteSource,
            UptimeStats,
            LatencyBucket,
            LatencySeries,
            Incident,
            AlertBinding,
            TargetAlerts,
            TagCount,
            DashboardSummary,
            TargetsSummary,
            StatusBreakdown,
            Last24hSummary,
            SystemSummary,
            BulkActionRequest,
            BulkAction,
            BulkActionResponse,
            BulkActionFailure,
            TestRequest,
            TestResponse,
            PageEnvelope<Target>,
            PageEnvelope<CheckResult>,
            PageEnvelope<Incident>,
            PageEnvelope<TagCount>,
            PublicApiError,
            PublicApiErrorBody,
            PublicStatusPage,
            OverallStatus,
            OverallState,
            PublicComponentGroup,
            PublicComponent,
            PublicComponentStatus,
            DayState,
            PublicIncident,
            PublicIncidentUpdate,
            IncidentSeverity,
            IncidentStatusPhase,
            PublicMaintenance,
            PublicMaintenanceList,
            ComponentHistoryResponse,
            PageEnvelope<PublicIncident>,
            NewMaintenanceWindow,
            MaintenanceWindowUpdate,
            MaintenanceWindow,
            MaintenanceFilter,
            PageEnvelope<MaintenanceWindow>,
            NotificationChannel,
            NewNotificationChannel,
            NotificationChannelUpdate,
            ChannelConfig,
            ChannelKind,
            handlers::notification_channels::TestNotificationResponse,
            IncidentNarrationUpdate,
            NewIncidentUpdate,
            OpsIncident,
            IncidentEvent,
            IncidentEventKind,
            ActorType,
            IncidentState,
            IncidentUrgency,
            IncidentOrigin,
            IncidentVisibility,
            NewManualIncident,
            handlers::incidents::IncidentDetail,
            handlers::incidents::LifecycleBody,
            handlers::incidents::AssignBody,
            handlers::incidents::NoteBody,
            EscalationPolicy,
            EscalationPolicySummary,
            EscalationStep,
            EscalationTarget,
            EscalationTargetType,
            NewEscalationPolicy,
            NewEscalationStep,
            NewEscalationTarget,
            handlers::escalation_policies::PolicyBinding,
            CreateOrgRequest,
            UpdateOrgRequest,
            OrgView,
            OrgMemberView,
            CheckSlugResponse,
            SwitchActiveOrgRequest,
            handlers::usage::QuotaUsage,
            handlers::usage::PlanSummary,
            handlers::usage::OrgQuotas,
            handlers::usage::UsagePolicy,
            handlers::usage::UsageRateLimits,
            handlers::usage::UsageFeatures,
            handlers::usage::OrgUsageResponse,
            handlers::usage::MeUsageResponse,
            crate::domain::MonitorShare,
            crate::domain::NewMonitorShare,
            handlers::status_page::StatusPageView,
            handlers::status_page::CreatePageRequest,
            handlers::status_page::UpdatePageRequest,
            handlers::status_page::BrandingInput,
            handlers::status_page::ReorderRequest,
            handlers::status_page::LogoResponse,
            crate::domain::StatusPageComponent,
            crate::domain::NewStatusPageComponent,
            crate::domain::StatusPageComponentUpdate,
            crate::domain::StatusPageId,
            crate::domain::PublicOrgBranding,
            Role,
            crate::storage::postgres_secrets::RedactedTarget,
            handlers::account::UserDataExport,
            handlers::account::UserExport,
            handlers::account::OAuthIdentityExport,
            handlers::account::SessionMetadata,
            handlers::account::ApiTokenMetadata,
            handlers::account::OwnedOrgExport,
            handlers::account::OrgExport,
            handlers::account::IncidentExport,
            handlers::account::MaintenanceExport,
            handlers::account::StatusPageExport,
            handlers::account::StatusPageComponentExport,
            handlers::account::MemberMetadata,
            handlers::account::MembershipExport,
            handlers::account::LoginAttemptExport,
            handlers::account::AuditEntryExport,
            handlers::account::DeletionConfirmation,
            handlers::api_tokens::NewApiTokenRequest,
            handlers::api_tokens::NewApiTokenResponse,
            handlers::api_tokens::ApiTokenView,
            handlers::api_tokens::RenameApiTokenRequest,
        ),
    ),
    tags(
        (name = "health",        description = "Liveness and readiness probes"),
        (name = "targets",       description = "Target CRUD and operations"),
        (name = "results",       description = "Check results, uptime, incidents"),
        (name = "tags",          description = "Tag inventory"),
        (name = "dashboard",     description = "Fleet-wide aggregated views"),
        (name = "public_status", description = "Public, unauthenticated status page surface"),
        (name = "maintenance",   description = "Scheduled maintenance windows (operator)"),
        (name = "notification-channels", description = "Notification delivery destinations (operator)"),
        (name = "incidents",     description = "Incident narration and timeline (operator)"),
        (name = "escalation",    description = "Escalation policies + monitor/org bindings (owner)"),
        (name = "orgs",          description = "Organisation management and membership"),
        (name = "status-pages",  description = "Public status page management (per-org, owner-managed)"),
        (name = "shares",        description = "Read-only single-monitor share links (member-managed)"),
        (name = "account",       description = "GDPR data export and account deletion"),
        (name = "api-tokens",    description = "Personal API token management (browser session only)"),
    ),
)]
pub struct ApiDoc;
