#!/usr/bin/env bash
# Stand up (or tear down) the local multi-region topology: the dev control
# plane plus two real regional agents running in docker.
#
#   scripts/dev-regions.sh         # up: mint regions + agents, start containers
#   scripts/dev-regions.sh down    # delete the harness agents/regions + stop
#
# The harness uses its OWN region ids (eu-helsinki, apac-sg) so it never
# collides with scripts/seed-fixtures.sh, which owns eu-west/us-east/ap-south
# for its fake multi-region UI fixtures. The two are independent: seed for
# fixture data, this for real agents you can assign monitors to.
#
# Up mints a fresh agent token per region via the operator API, writes the
# tokens to .dev-agents.env (gitignored), then starts the agent containers from
# compose.dev.agents.yml. Idempotent: re-running deletes the previous harness
# agents first, so tokens never accumulate.
#
# Prereqs: the dev control plane is up (`just up-app`, or native `just run`
# with UPTIMEPAGE_SERVER__API_BIND=0.0.0.0:8080) and the operator surface is on
# (UPTIMEPAGE_OPERATOR__ADMIN_TOKEN set — compose.dev.yml sets a dev value).
#
# Env overrides:
#   BASE            control-plane URL the SCRIPT calls (default: http://app.lvh.me:8080)
#   OPERATOR_TOKEN  operator secret                    (default: dev-operator-token)
#   AGENT_CONTROL_PLANE_URL  URL the AGENT CONTAINERS use to reach the control
#                   plane. Default http://uptimepage:8080 (containerized CP via
#                   `just up-app`). For a native CP (`just run`) set this to
#                   http://host.docker.internal:8080.
set -euo pipefail

ACTION="${1:-up}"
BASE="${BASE:-http://app.lvh.me:8080}"
TOKEN="${OPERATOR_TOKEN:-dev-operator-token}"
AGENT_CP_URL="${AGENT_CONTROL_PLANE_URL:-http://uptimepage:8080}"
ENV_FILE=".dev-agents.env"
COMPOSE=(docker compose -f compose.dev.yml -f compose.dev.agents.yml)
AUTH=(-H "Authorization: Bearer ${TOKEN}")

# region id : agent name : env var holding the minted token
REGIONS=(
  "eu-helsinki:dev-harness-eu-helsinki:AGENT_EU_TOKEN"
  "apac-sg:dev-harness-apac-sg:AGENT_APAC_TOKEN"
)

command -v jq >/dev/null || { echo "error: jq is required" >&2; exit 2; }

echo "control plane: $BASE"
echo -n "waiting for /readyz "
for _ in $(seq 1 60); do
  if curl -fsS -o /dev/null "$BASE/readyz" 2>/dev/null; then break; fi
  echo -n .; sleep 1
done
echo
curl -fsS -o /dev/null "$BASE/readyz" || { echo "error: control plane not ready at $BASE" >&2; exit 1; }

# Verify the operator surface is reachable (401/404 => token wrong or surface off).
code=$(curl -sS -o /dev/null -w '%{http_code}' "${AUTH[@]}" "$BASE/operator/regions")
[[ $code == 200 ]] || { echo "error: /operator/regions returned $code (check OPERATOR_TOKEN / admin_token)" >&2; exit 1; }

# Delete every harness agent (any region) so the row's FK no longer pins its
# region — lets re-runs start clean and lets seed-fixtures wipe its regions.
purge_agents() {
  curl -fsS "${AUTH[@]}" "$BASE/operator/agents" \
    | jq -r '.[] | select(.name|startswith("dev-harness-")) | .id' \
    | while read -r id; do
        [[ -n $id ]] && curl -fsS -o /dev/null -X DELETE "${AUTH[@]}" "$BASE/operator/agents/$id" \
          && echo "  removed agent $id"
      done
}

if [[ $ACTION == down ]]; then
  echo "stopping agent containers…"
  "${COMPOSE[@]}" --profile agents rm -sf agent-eu agent-apac >/dev/null 2>&1 || true
  echo "deleting harness agents…"
  purge_agents
  echo "deleting harness regions…"
  for entry in "${REGIONS[@]}"; do
    region=${entry%%:*}
    curl -sS -o /dev/null -X DELETE "${AUTH[@]}" "$BASE/operator/regions/$region" || true
  done
  rm -f "$ENV_FILE"
  echo "down."
  exit 0
fi

echo "removing any prior harness agents…"
purge_agents

: > "$ENV_FILE"
echo "# Generated by scripts/dev-regions.sh — agent tokens for the local harness." >> "$ENV_FILE"
echo "AGENT_CONTROL_PLANE_URL=$AGENT_CP_URL" >> "$ENV_FILE"

for entry in "${REGIONS[@]}"; do
  IFS=: read -r region name var <<<"$entry"

  # Ensure the region exists (201 created or 409 already-there are both fine).
  rc=$(curl -sS -o /dev/null -w '%{http_code}' -X POST "${AUTH[@]}" \
        -H 'Content-Type: application/json' \
        -d "{\"id\":\"$region\",\"name\":\"$region\"}" "$BASE/operator/regions")
  [[ $rc == 201 || $rc == 409 ]] || { echo "error: create region $region returned $rc" >&2; exit 1; }

  # Mint a fresh agent; the token is in the response body exactly once.
  body=$(curl -fsS -X POST "${AUTH[@]}" -H 'Content-Type: application/json' \
          -d "{\"region\":\"$region\",\"name\":\"$name\"}" "$BASE/operator/agents")
  tok=$(echo "$body" | jq -r '.token')
  [[ $tok == sm_agent_* ]] || { echo "error: no token minted for $region: $body" >&2; exit 1; }
  echo "$var=$tok" >> "$ENV_FILE"
  echo "  region $region -> agent $name minted"
done

echo "tokens written to $ENV_FILE"
echo "starting agents (first run builds the agent image — slow)…"
"${COMPOSE[@]}" --env-file "$ENV_FILE" --profile agents up -d --build agent-eu agent-apac

cat <<EOF

agents up (regions: eu-helsinki, apac-sg). next:
  - assign a monitor to a region: monitor form -> Regions, or
      PUT /api/v1/targets/{id}/regions  (needs an owner session — 'just dev-login')
  - watch agents:   just dev-regions-logs
  - per-region data: monitor detail view -> region selector / by-region table
  - tear down:      just dev-regions-down
EOF
